#!/bin/sh
# Basic configuration file in shell
#

# Setting macro
alias opt='_opt $1'
_opt(){
	[ "$1" = "$2" ] && printf '%s' "$3" && return 0;
	[ ! -n "$3" ]   && printf '%s\n' "$1"
	return 1;
}

# Settings go here, all lines but the last
# must have the double pipe (OR).
settings(){

	#   Setting name  Value
	opt "TEST_FLAG"   123 ||
	opt "TEST_FLAG"	  124 ||
	opt "TEST_FLAG_2" 124
}
