#!/bin/sh
# Basic configuration file in shell
#

# Testing function
function flag_function(){
	echo "!!$@!!"
}

# The load.c file can load properties in the
# following format. All lines but the last must
# contain the chaining "||" (OR) operator.
function SETTINGS(){

	#   Setting name | Value
	opt "KERNEL_VER"  "$(uname -r)" ||
	opt "TEST_FLAG_1"  "flag 1" ||
	opt "TEST_FLAG_2"  "$(flag_function flag 3 )" ||
	opt "TIME"         "$(date)"
}
